// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqcwoqxuhxswvnzrbdea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxY3dvcXh1aHhzd3ZuenJiZGVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODY4MDEsImV4cCI6MjA2OTU2MjgwMX0.naPzSL_jvmMrhxbxiHjwUL1lVUI0aYtWmrMRZBtOqOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});